runtime: java11
instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

automatic_scaling:
  min_instances: 0

inbound_services:
  - warmup
